# frozen_string_literal: true

# Copyright (c) 2015, Regents of the University of Michigan.
# All rights reserved. See LICENSE.txt for details.

require "yaml"
require "delegate"
require "active_support"
require "active_support/core_ext"
require "httparty"

require "spectrum/config/version"
require "spectrum/config/hierarchy"

require "spectrum/search_engines/primo/info"
require "spectrum/search_engines/primo/lib_key"
require "spectrum/search_engines/primo/doc"
require "spectrum/search_engines/primo/docs"
require "spectrum/search_engines/primo/highlights"
require "spectrum/search_engines/primo/timelog"
require "spectrum/search_engines/primo/facet_value"
require "spectrum/search_engines/primo/facet"
require "spectrum/search_engines/primo/facets"
require "spectrum/search_engines/primo/response"
require "spectrum/search_engines/primo/engine"
require "spectrum/search_engines/primo"

require "spectrum/config/base_source"
require "spectrum/config/solr_source"
require "spectrum/config/summon_source"
require "spectrum/config/primo_source"
require "spectrum/config/source"

require "spectrum/config/config"
require "spectrum/config/config_list"
require "spectrum/config/mapped_config_list"
require "spectrum/config/metadata"
require "spectrum/config/focus"
require "spectrum/config/focus_list"
require "spectrum/config/source_list"
require "spectrum/config/search_field"
require "spectrum/config/search_field_list"
require "spectrum/config/blacklight"
require "spectrum/config/href"
require "spectrum/config/holdings_url"
require "spectrum/config/get_this_url"

require "spectrum/config/csl_base"
require "spectrum/config/csl_literal"
require "spectrum/config/csl_array"
require "spectrum/config/csl_type"
require "spectrum/config/csl_date"
require "spectrum/config/csl_author"
require "spectrum/config/csl_null"
require "spectrum/config/csl"
require "spectrum/config/csl_aggregator"

require "spectrum/config/z3988_literal"
require "spectrum/config/z3988_rft_val_fmt"
require "spectrum/config/z3988_rft_genre"
require "spectrum/config/z3988_constant"
require "spectrum/config/z3988_null"
require "spectrum/config/z3988"

require "spectrum/config/metadata_component"
require "spectrum/config/plain_metadata_component"
require "spectrum/config/icon_metadata_component"
require "spectrum/config/mailto_metadata_component"
require "spectrum/config/image_metadata_component"
require "spectrum/config/href_linked_metadata_component"
require "spectrum/config/structured_data_href_linked_metadata_component"
require "spectrum/config/browse_metadata_component"
require "spectrum/config/search1_metadata_component"
require "spectrum/config/search2_metadata_component"
require "spectrum/config/search_browse_metadata_component"
require "spectrum/config/search_browse2_metadata_component"
require "spectrum/config/delimited_search1_metadata_component"
require "spectrum/config/quoted_search1_metadata_component"
require "spectrum/config/quoted_search2_metadata_component"
require "spectrum/config/quoted_search3_metadata_component"
require "spectrum/config/specified_search_metadata_component"

require "spectrum/config/highly_recommended"
require "spectrum/config/sort"
require "spectrum/config/sort_list"

require "spectrum/config/marc_matcher_where_clause"
require "spectrum/config/marc_matcher_where_is"
require "spectrum/config/marc_matcher_where_not"
require "spectrum/config/marc_matcher_where_exists"
require "spectrum/config/marc_matcher_where_start_with"
require "spectrum/config/marc_matcher_where_end_with"
require "spectrum/config/marc_matcher_where_not_end_with"
require "spectrum/config/marc_matcher_where"

require "spectrum/config/marc"
require "spectrum/config/marc_matcher"

require "spectrum/config/condition"

require "spectrum/config/aggregator"
require "spectrum/config/collapsing_aggregator"
require "spectrum/config/list_aggregator"
require "spectrum/config/field_aggregator"
require "spectrum/config/labeling_aggregator"
require "spectrum/config/filtered_labeling_aggregator"
require "spectrum/config/online_resource_aggregator"
require "spectrum/config/advanced_filtering_aggregator"

require "spectrum/config/field"
require "spectrum/config/basic_field"
require "spectrum/config/constant_field"
require "spectrum/config/concat_field"
require "spectrum/config/priority_field"
require "spectrum/config/bookplate_field"
require "spectrum/config/marcxml_field"
require "spectrum/config/marcjson_field"
require "spectrum/config/parallel_merge_field"
require "spectrum/config/concatenate_merge_field"
require "spectrum/config/conditional_merge_field"
require "spectrum/config/pseudo_facet_field"
require "spectrum/config/mapped_pseudo_facet_field"
require "spectrum/config/summon_access_url_field"
require "spectrum/config/summon_date_field"
require "spectrum/config/summon_year_field"
require "spectrum/config/summon_month_field"
require "spectrum/config/summon_day_field"
require "spectrum/config/solr_year_field"
require "spectrum/config/solr_month_field"
require "spectrum/config/solr_day_field"
require "spectrum/config/formatted_catalog_published_field"
require "spectrum/config/formatted_article_published_field"
require "spectrum/config/formatted_page_range_field"
require "spectrum/config/formatted_full_title_field"
require "spectrum/config/highly_recommended_field"
require "spectrum/config/field_list"
require "spectrum/config/resource_access_field"
require "spectrum/config/summon_resource_access_field"
require "spectrum/config/holdings_resource_access_field"
require "spectrum/config/primo_resource_access_field"
require "spectrum/config/more_information_field"
require "spectrum/config/times_cited_field"
require "spectrum/config/times_cited2_field"
require "spectrum/config/primo_times_cited_field"

require "spectrum/config/facet_parents"
require "spectrum/config/facet"
require "spectrum/config/facet_list"

require "spectrum/config/field_facet"

require "spectrum/config/filter"
require "spectrum/config/filter_list"

require "spectrum/config/bookplate"
require "spectrum/config/bookplate_list"

require "spectrum/config/credentials"
require "spectrum/config/action"
require "spectrum/config/action_list"

module Spectrum
  module Config
    # Your code goes here...
  end
end
