---
version: "3.7"
services:
  web:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec rails s -p ${PUMA_PORT} -b ${PUMA_BIND}
    env_file:
      - .env
    volumes:
    - .:/app
    - bundle:/bundle
    ports:
    - "3000:3000"
volumes:
  bundle:
