---
version: '3'
services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    command: script/docker-startup
    env_file:
      - .env-dev-values
      - .env
    volumes:
    - .:/app
    - bundle:/bundle
    ports:
    - "3000:3000"
    user: ${UID}:${GID}

  redis:
    image: redis
    ports:
     - "6379:6379"

  catalog-solr:
    image: ghcr.io/mlibrary/catalog-solr-unstable:latest 
    ports:
     - "8026:8026"
    volumes:
      - catalog:/var/solr

  library-web-solr:
    image: ghcr.io/mlibrary/library-web-solr:latest
    ports:
      - "8080:8080"
    volumes:
      - library-web:/var/solr

volumes:
  bundle:
  catalog:
  library-web:
