---
version: "3.7"
services:
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        - UID=${UID}
        - GID=${GID}
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p ${BIND_PORT} -b ${BIND_IP}'
    env_file:
      - .env
    #environment:
      #- SPECTRUM_CATALOG_SOLR_URL=http://solr:8026/solr/biblio
    volumes:
    - .:/app
    - bundle:/bundle
    ports:
    - "3000:3000"
    user: ${UID}:${GID}

  #solr:
    #image: ghcr.io/mlibrary/library-solr:latest 
    #ports:
     #- "8026:8026"

volumes:
  bundle:
