---
id: articlesplus
metadata:
  name: Articles
  short_desc: "Search for articles, books, journals, and more"
source: summon
href:
  field: id
  prefix: http://www.lib.umich.edu/articles/details/
default_sort: summon_relevance
sorts:
  relevance: summon_relevance
  date_asc: summon_date_asc
  date_desc: summon_date_desc
fields:
  - summon_title
  - subtitle
  - format
  - abstract
  - ap_author
  - summon_date
  - article_published_brief
  - page_range
  - publisher
  - publication_title
  - publication_title_abbrev
  - publication_title_alternate
  - publication_place
  - volume
  - issue
  - genre
  - summon_issn
  - summon_eissn
  - summon_isbn
  - summon_eisbn
  - doi
  - summon_language
  - summon_subject
  - brief_description
  - type
  #- subject
  - summon_year
  - summon_month
  - summon_day
  - summon_access_url
  - start_page
  - end_page
  - pages
  - summon_links
  - summon_source
  - summon_source_type
  - summon_database_xml
  - summon_series
  - summon_isn
  - link_model
  - fulltext
  - isi_cited_references_uri
  - summon_resource_access
  - times_cited
  - times_cited2
  - summon_openurl
# Not rendered
  - id
# For citation generation
  - summon_csl_type
# For searching
  - all_fields
  - pmid

facets:
  IsScholarly: is_scholarly
  exclude_newspapers: exclude_newspapers
  IsFullText: available_online
  IsOpenAccess: is_open_access
  holdings_only: holdings_only
  ContentType: format
  SubjectTerms: summon_subject
  PublicationDate: publication_date
  summon_language: summon_language
