---
id: journals
id_field: entity_id
metadata:
  name: Online Journals
  short_desc: "Search for online journals."
source: website
filters:
  - "+source:ejournals-mirlyn"
highly_recommended:
  field: academic_discipline
  sort_uid: title_asc
solr_params:
  # title
  f.search_title.qf: sort_title^12 stitle^12 title_unstemmed^6 all_titles_unstemmed^3 title^2 alt^1
  f.search_title.pf: title alt
  f.search_title.mm: 75%

  # title_starts_with
  f.search_title_starts_with.qf: title_ngram
  f.search_title_starts_with.pf: title_ngram
  f.search_title_starts_with.mm: 100%

  # callno_starts_with
  f.search_call_number_starts_with.qf: callnosearch
  f.search_call_number_starts_with.pf: callnosearch
  f.search_call_number_starts_with.mm: 100%


  # isn
  f.search_isn.qf: issn
  f.search_isn.pf: issn

  # publisher
  f.search_publisher.qf: pvc_text
  f.search_publisher.pf: pvc_text
  f.search_publisher.mm: 100%

  # academic_discipline
  f.search_academic_discipline.qf: og_groups_both^10 subject
  f.search_academic_discipline.pf: og_groups_both^10 subject
  f.search_academic_discipline.mm: 100%

  # subject
  f.search_subject.qf: og_groups_both^10 subject
  f.search_subject.pf: og_groups_both^10 subject
  f.search_subject.mm: 100%

  # default
  qf: title_unstemmed^10 title^7 all_titles_unstemmed^8 all_titles^6 issn^10 content^2
  mm: 25%
  pf: title all_titles content
  defType: edismax
  qt: edismax

default_sort: relevance
sorts:
  relevance: relevance
  title_asc: title_asc
  title_desc: title_desc
# mapping is "External Name: Internal UID"
# i.e. solr_field_name => uid used in fields.yml
has_holdings: false
fields:
  - entity_id
  - content
  - title
  - online_journal_format
  - issn
  - journal_academic_discipline
  - holdings
  - access
  - access_url
  - alt_title
  - TBD
  - journal_coverage
  - ejournal_links
  - subject
  - isn
  - title_starts_with
  - call_number_starts_with
  - highly_recommended
  - journal_resource_access
  - z3988_rft_val_fmt
  - z3988_rft_genre
  - z3988_sid
  - journals_rfr_id

facets:
  - db_academic_discipline
  - language
  - title_initial
