---
id: articles
metadata:
  name: Articles
  short_desc: "Search for articles, books, journals, and more"
source: primo
sorts:
  relevance: summon_relevance
  date_asc: summon_date_asc
  date_desc: summon_date_desc
fields:
- addsrcrecordid
- title
- format
- author
- abstract
- creationdate
- pages
- publisher
- jtitle
- volume
- issue 
- genre
- issn
- summon_isbn
- eissn
- eisbn
- doi
- pmid
- oclcid

facets:
- jtitle
- lang
- topic
- rtype
- domain
- tlevel
- newrecords
- creationdate
#- creatorcontrib
#- collection
