version: '3.4'

services:
  app:
    image: ruby:3.1.0
    environment:
      - BUNDLE_PATH=/bundle
      - BUNDLE_CONFIG=/app/.bundle/config
    command: tail -f /dev/null
    working_dir: /app
    volumes:
      - .:/app
      - bundler_data:/bundle
    tmpfs:
      - /tmp

volumes:
  bundler_data:
