---
aleph_x_url: <%= ENV['SPECTRUM_ALEPH_X_URL'] %>
base_url: <%= ENV['SPECTRUM_ALEPH_BASE_URL'] %>
rest_url: <%= ENV['SPECTRUM_ALEPH_REST_URL'] %>
bib_library: MIU01
adm_library: MIU50
services:
  borrower:
    ill:
      - "01AF"
      - "01EM"
      - "01FA"
      - "01GE"
      - "01GF"
      - "01HH"
      - "01JF"
      - "01RF"
      - "01SE"
      - "01SW"
      - "01VS"
      - "02CR"
      - "02D1"
      - "02D2"
      - "02EP"
      - "02OJ"
      - "02RS"
      - "02ST"
      - "02WD"
      - "03CD"
      - "03GR"
      - "04SU"
      - "04UN"
    7fast:
      - "01AF"
      - "01EM"
      - "01FA"
      - "01GE"
      - "01GF"
      - "01HH"
      - "01JF"
      - "01RF"
      - "01SE"
      - "01SW"
      - "01VS"
      - "02CR"
      - "02D1"
      - "02D2"
      - "02EP"
      - "02OJ"
      - "02RS"
      - "02ST"
      - "02WD"
      - "03CD"
      - "03GR"
      - "04UN"
    other:
      - "10DB"
      - "05G2"
      - "04SU"
      - "04MR"
      - "02TS"
      - "02SP"
      - "02SF"
      - "02RC"
      - "02OJ"
      - "02G1"
      - "02DO"
      - "02AL"
      - "01RL"
      - "01MI"
      - "01DC"
      - "01CI"
      - "01AG"
status:
  - start_with: On shelf
    intent: success
    icon: check_circle
  - start_with: On Shelf
    intent: success
    icon: check_circle
  - start_with: Building use only
    intent: success
    icon: check_circle
  - start_with: Reading Room Use Only
    intent: success
    icon: check_circle
  - start_with: Access at
    intent: success
    icon: check_circle
  - start_with: Documents Workstation
    intent: success
    icon: check_circle
  - start_with: Electronic Access Only
    intent: success
    icon: check_circle
  - start_with: Access at
    intent: success
    icon: check_circle
  - start_with: In Special Collections
    intent: success
    icon: check_circle
  - start_with: NSDS Lab (Documents Center)
    intent: success
    icon: check_circle
  - start_with: New Release
    intent: success
    icon: check_circle
  - start_with: On New Book Shelf
    intent: success
    icon: check_circle
  - start_with: Received-Enroute to Divisional
    intent: success
    icon: check_circle
  - start_with: Remote Storage
    intent: success
    icon: check_circle

  - start_with: Checked out
    intent: warning
    icon: warning
  - start_with: Extended loan
    intent: warning
    icon: warning
  - start_with: Recalled
    intent: warning
    icon: warning
  - start_with: Askwith Reserve
    intent: warning
    icon: warning
  - start_with: Being Processed For Reserve
    intent: warning
    icon: warning
  - start_with: Being Repaired. Ask staff
    intent: warning
    icon: warning
  - start_with: Closed shelving.
    intent: warning
    icon: warning
  - start_with: Final Processing.
    intent: warning
    icon: warning
  - start_with: In Conservation
    intent: warning
    icon: warning
  - start_with: In Preservation
    intent: warning
    icon: warning
  - start_with: Int. Studies Cataloging
    intent: warning
    icon: warning
  - start_with: Not Available - Ask Staff (HC)
    intent: warning
    icon: warning
  - start_with: On Display
    intent: warning
    icon: warning
  - start_with: On Loan to NELP-Ask at GL Circ
    intent: warning
    icon: warning
  - start_with: Replacement Ordered
    intent: warning
    icon: warning
  - start_with: Returned from Conservation
    intent: warning
    icon: warning
  - start_with: SE Asia In Process-Hatcher
    intent: warning
    icon: warning
  - start_with: Scholars Workstation.Ask at IC
    intent: warning
    icon: warning
  - start_with: Send to Cataloging
    intent: warning
    icon: warning
  - start_with: Sent for Scanning
    intent: warning
    icon: warning
  - start_with: Sent from Scanning
    intent: warning
    icon: warning
  - start_with: Sent to Conservation
    intent: warning
    icon: warning
  - start_with: Sent to Labeling
    intent: warning
    icon: warning
  - start_with: Slavic In Process
    intent: warning
    icon: warning
  - start_with: Subject and classification
    intent: warning
    icon: warning
  - start_with: Technical Department
    intent: warning
    icon: warning

  - start_with: Not arrived
    intent: error
    icon: error
  - start_with: Claimed
    intent: error
    icon: error
  - start_with: Requested
    intent: error
    icon: error
  - start_with: Asia Library Cataloging
    intent: error
    icon: error
  - start_with: At Bindery
    intent: error
    icon: error
  - start_with: At Book Repair
    intent: error
    icon: error
  - start_with: At Labeling
    intent: error
    icon: error
  - start_with: At Pamphlet Bindery
    intent: error
    icon: error
  - start_with: Cancelled
    intent: error
    icon: error
  - start_with: Duplicate to be Withdrawn
    intent: error
    icon: error
  - start_with: In process
    intent: error
    icon: error
  - start_with: In transit from
    intent: error
    icon: error
  - start_with: Missing
    intent: error
    icon: error
  - start_with: No Longer Available
    intent: error
    icon: error
  - start_with: Not Available
    intent: error
    icon: error
  - start_with: Not Published
    intent: error
    icon: error
  - start_with: Not available
    intent: error
    icon: error
  - start_with: On Loan for
    intent: error
    icon: error
  - start_with: On Order
    intent: error
    icon: error
  - start_with: Order Initiation
    intent: error
    icon: error
  - start_with: Order Received
    intent: error
    icon: error
  - start_with: Pulled for Binding
    intent: error
    icon: error
  - start_with: Sent for Deacidification
    intent: error
    icon: error
  - start_with: UGL - Not Available
    intent: error
    icon: error
  - start_with: Unavailable - Ask at ILL
    intent: error
    icon: error
  - start_with: Withdrawn
    intent: error
    icon: error
