- uid: SPAUL
  desc: Spaulding Trust Fund
  #url: http://www.lib.umich.edu/funds/hunt.html
  image: /static/bookplates/Stephen_Spaulding.png
- uid: HUNT
  desc: Lieutenant John Henry Hunter Memorial Fund
  #url: http://www.lib.umich.edu/funds/hunt.html
  image: /static/bookplates/Hunter_digital.png
- uid: BRAND
  desc: Brandt Fund
  #url: http://www.lib.umich.edu/funds/brand.html
  image: /static/bookplates/Brandt.png 
- uid: LITT
  desc: Lucius N. Littauer Judaica Book Fund
  #url: http://www.lib.umich.edu/funds/litt.html
  image: /static/bookplates/Littauer.png 
- uid: BATRB
  desc: Octavia Williams Bates Bequest
  #url: http://www.lib.umich.edu/funds/batrb.html
  image: /static/bookplates/Bates.png 
- uid: HARRB
  desc: Galen C. Hartman Library Fund
  #url: http://www.lib.umich.edu/funds/harrb.html
  image: /static/bookplates/Hartman.png 
- uid: EAST
  desc: Mona A. East Book Endowment Fund
  #url: http://www.lib.umich.edu/funds/east.html
  image: /static/bookplates/EAST_Endowment.png 
- uid: TYWU
  desc: Ta-You Wu Trust Fund
  #url: http://www.lib.umich.edu/funds/east.html
  image: /static/bookplates/interimtywu.png
