---
academic_discipline:
  "Academic and Specialized News": ["News & Current Events"]
  "Aerospace Engineering": ["Engineering"]
  "African American Studies": ["Social Sciences"]
  "African Studies": ["International Studies"]
  "Allergy and Clinical Immunology": ["Health Sciences"]
  "American Culture": ["Humanities"]
  "Analytical Chemistry": ["Chemistry"]
  "Anesthesiology": ["Health Sciences"]
  "Anthropology": ["Social Sciences"]
  "Arab-American Studies": ["Social Sciences"]
  "Archaeology": ["Social Sciences"]
  "Architecture": ["Arts"]
  "Archives & Record Management": ["Information Science"]
  "Archives and Manuscripts": ["General Information Sources"]
  "Armenian Studies": ["European Studies"]
  "Art and Design": ["Arts"]
  "Art History": ["Arts"]
  "Asian Languages and Cultures": ["Humanities"]
  "Asian Studies": ["International Studies"]
  "Asian/Pacific Islander American Studies": ["Social Sciences"]
  "Astronomy and Astrophysics": ["Science"]
  "Athletic Training": ["Kinesiology and Sports"]
  "Automotive Engineering": ["Engineering"]
  "Biological Chemistry": ["Chemistry","Health Sciences"]
  "Biology": ["Science"]
  "Biomedical Engineering": ["Engineering","Health Sciences"]
  "Biostatistics": ["Health Sciences"]
  "Books": ["General Information Sources"]
  "Botany": ["Biology"]
  "British and Irish Studies": ["European Studies"]
  "Business (General)": ["Business"]
  "Business News": ["News & Current Events"]
  "Cardiovascular Medicine": ["Health Sciences"]
  "Careers": ["Business"]
  "Central Asian and Caucasian Studies": ["Asian Studies"]
  "Chemical Engineering": ["Engineering","Science"]
  "Chemistry": ["Science"]
  "Chinese Studies": ["Asian Studies"]
  "Civil Engineering": ["Engineering"]
  "Classical Studies": ["Humanities"]
  "Climate Sciences": ["Engineering","Science"]
  "Communication Studies": ["Social Sciences"]
  "Companies and Industry": ["Business"]
  "Computer Science": ["Engineering"]
  "Conservative and Liberal Perspectives": ["News & Current Events"]
  "Conservative Perspectives": ["Conservative and Liberal Perspectives"]
  "Czech and Slovak Studies": ["European Studies"]
  "Dance": ["Arts"]
  "Dentistry": ["Health Sciences"]
  "Dermatology": ["Health Sciences"]
  "Dictionaries": ["General Information Sources"]
  "Disability Studies": ["Social Sciences"]
  "Earth and Environmental Sciences": ["Science"]
  "East Asian Studies": ["Asian Studies"]
  "Ecology and Evolutionary Biology": ["Biology"]
  "Economics": ["Social Sciences"]
  "Education": ["Social Sciences"]
  "Electrical Engineering": ["Engineering"]
  "Emergency Medicine": ["Health Sciences"]
  "Encyclopedias": ["General Information Sources"]
  "Endocrinology": ["Health Sciences"]
  "Energy": ["Engineering"]
  "Engineering (General)": ["Engineering"]
  "Engineering Education": ["Engineering"]
  "English Language and Literature": ["Humanities"]
  "Entrepreneurship": ["Business","Engineering"]
  "Environment and Sustainability": ["Science"]
  "Environmental Engineering": ["Engineering"]
  "Environmental Health Sciences": ["Health Sciences"]
  "Epidemiology": ["Health Sciences"]
  "European Studies": ["International Studies"]
  "European Union Studies": ["European Studies"]
  "Family Medicine": ["Health Sciences"]
  "Film and Video Studies": ["Arts"]
  "Finance": ["Business"]
  "French Language and Literatures": ["Romance Languages and Literatures"]
  "French Studies": ["European Studies"]
  "Gastroenterology": ["Health Sciences"]
  "Gay/Lesbian/Bisexual/Transgender Studies": ["Social Sciences"]
  "General and Comparative Literature": ["Humanities"]
  "General Encyclopedias": ["Encyclopedias"]
  "Genetics": ["Science"]
  "Geography and Maps": ["Social Sciences"]
  "Geospatial Data": ["Statistics and Data Sets"]
  "Geriatric Medicine": ["Health Sciences"]
  "Germanic Languages and Literatures": ["Humanities"]
  "Germanic Studies": ["European Studies"]
  "Government Information": ["Government, Politics & Law"]
  "Grants and Fundraising": ["General Information Sources"]
  "Health Behavior and Health Equity": ["Health Sciences"]
  "Health Management and Policy": ["Health Sciences"]
  "Hematology and Oncology": ["Health Sciences"]
  "Historical News Sources": ["News & Current Events"]
  "History (General)": ["Humanities"]
  "Human Computer Interaction": ["Information Science"]
  "Human Genetics": ["Health Sciences"]
  "Humanities (General)": ["Humanities"]
  "Iberian Studies": ["European Studies"]
  "Images and Videos": ["General Information Sources"]
  "Industrial and Operations Engineering": ["Engineering"]
  "Infectious Diseases": ["Health Sciences"]
  "Information Science": ["Social Sciences"]
  "Inorganic Chemistry": ["Chemistry"]
  "Integrative Medicine": ["Health Sciences"]
  "Internal Medicine": ["Health Sciences"]
  "International Business": ["Business"]
  "International Government Information": ["Government Information"]
  "International News": ["News & Current Events"]
  "International Public Policy": ["Public Policy"]
  "Italian Language and Literatures": ["Romance Languages and Literatures"]
  "Italian Studies": ["European Studies"]
  "Japanese Studies": ["Asian Studies"]
  "Journals and Magazines": ["General Information Sources"]
  "Judaic Studies": ["Humanities","Social Sciences"]
  "Kinesiology and Sports": ["Health Sciences","Social Sciences"]
  "Korean Studies": ["Asian Studies"]
  "Landscape Architecture": ["Arts","Science"]
  "Latin American and Caribbean Studies": ["International Studies"]
  "Latina/o Studies": ["Social Sciences"]
  "Law and Legal Studies": ["Government, Politics & Law"]
  "Liberal Perspectives": ["Conservative and Liberal Perspectives"]
  "Library Science": ["Information Science"]
  "Linguistics": ["Humanities"]
  "Management": ["Business"]
  "Manufacturing": ["Engineering"]
  "Marketing": ["Business"]
  "Materials Science and Engineering": ["Engineering"]
  "Mathematics": ["Science"]
  "Mechanical Engineering": ["Engineering"]
  "Medical Education": ["Health Sciences"]
  "Medicine (General)": ["Health Sciences"]
  "Michigan News": ["News & Current Events"]
  "Microbiology and Immunology": ["Biology","Health Sciences"]
  "Middle Eastern, Near Eastern and North African Studies": ["International Studies"]
  "Modern Greek Studies": ["European Studies"]
  "Molecular, Cellular and Developmental Biology": ["Biology","Health Sciences"]
  "Movement Science": ["Kinesiology and Sports"]
  "Multiple Perspectives": ["Conservative and Liberal Perspectives"]
  "Multiracial Studies": ["Social Sciences"]
  "Museum Studies": ["Humanities"]
  "Music": ["Arts"]
  "Native American Studies": ["Social Sciences"]
  "Naval Architecture and Marine Engineering": ["Engineering"]
  "Nephrology": ["Health Sciences"]
  "Neurology and Neurosciences": ["Health Sciences"]
  "Neurosurgery": ["Health Sciences"]
  "News Magazines": ["News & Current Events"]
  "Nuclear Engineering and Radiological Sciences": ["Engineering"]
  "Numeric (Micro-Level) Data": ["Statistics and Data Sets"]
  "Nursing": ["Health Sciences"]
  "Obstetrics and Gynecology": ["Health Sciences"]
  "Ophthalmology and Vision Sciences": ["Health Sciences"]
  "Organic Chemistry": ["Chemistry"]
  "Organizations and Businesses": ["General Information Sources"]
  "Orthopaedic Surgery": ["Health Sciences"]
  "Otolaryngology": ["Health Sciences"]
  "Pacific/Australia/New Zealand Studies": ["Asian Studies"]
  "Patents and Trademarks": ["Engineering","Government, Politics & Law"]
  "Pathology": ["Health Sciences"]
  "Pediatrics": ["Health Sciences"]
  "People (Biography and Contact Information)": ["General Information Sources"]
  "Pharmaceutical Engineering": ["Engineering"]
  "Pharmacy and Pharmacology": ["Health Sciences"]
  "Philosophy": ["Humanities"]
  "Photographs and Pictorial Works": ["Images and Videos"]
  "Physical Chemistry": ["Chemistry"]
  "Physical Education": ["Kinesiology and Sports"]
  "Physical Medicine and Rehabilitation": ["Health Sciences"]
  "Physics": ["Science"]
  "Physiology": ["Health Sciences","Science"]
  "Places": ["General Information Sources"]
  "Polish Studies": ["European Studies"]
  "Political Science": ["Government, Politics & Law"]
  "Population and Demography": ["Social Sciences"]
  "Portuguese Language and Literatures": ["Romance Languages and Literatures"]
  "Psychiatry": ["Health Sciences"]
  "Psychology": ["Social Sciences"]
  "Public Health (General)": ["Health Sciences"]
  "Public Policy": ["Government, Politics & Law"]
  "Pulmonary Medicine": ["Health Sciences"]
  "Radiation Oncology": ["Hematology and Oncology"]
  "Radiology": ["Health Sciences"]
  "Religious Studies": ["Humanities"]
  "Reviews (of Books, Movies, Plays, etc.)": ["General Information Sources"]
  "Rheumatology": ["Health Sciences"]
  "Robotics": ["Engineering"]
  "Romance Languages and Literatures": ["Humanities"]
  "Russian Studies": ["European Studies"]
  "Scandinavian Languages and Literatures": ["Humanities"]
  "Scandinavian Studies": ["European Studies"]
  "Science (General)": ["Science"]
  "Science Policy": ["Public Policy"]
  "Search Engines": ["General Information Sources"]
  "Slavic and East European Studies": ["European Studies"]
  "Slavic Languages and Literatures": ["Humanities"]
  "Social Sciences (General)": ["Social Sciences"]
  "Social Work": ["Social Sciences"]
  "Sociology": ["Social Sciences"]
  "South Asian Studies": ["Asian Studies"]
  "Southeast Asian Studies": ["Asian Studies"]
  "Southeast European Studies": ["European Studies"]
  "Space Sciences and Engineering": ["Engineering","Science"]
  "Spanish Language and Literatures": ["Romance Languages and Literatures"]
  "Sports": ["Kinesiology and Sports"]
  "Sports Management": ["Kinesiology and Sports"]
  "Standards": ["Engineering"]
  "State and Local Government Information": ["Government Information"]
  "State and Local Policy": ["Public Policy"]
  "Statistical (Macro-Level) Data": ["Statistics and Data Sets"]
  "Statistical Facts and Figures": ["General Information Sources"]
  "Statistics (Mathematical)": ["Science"]
  "Statistics and Data Sets": ["Government, Politics & Law","Social Sciences"]
  "Subject Encyclopedias": ["Encyclopedias"]
  "Surgery": ["Health Sciences"]
  "Theatre and Drama": ["Arts"]
  "Transportation": ["Engineering"]
  "U.S. Domestic Policy": ["Public Policy"]
  "U.S. Government Information": ["Government Information"]
  "U.S. News": ["News & Current Events"]
  "United States History": ["Humanities"]
  "Urban Planning": ["Social Sciences"]
  "Urology": ["Health Sciences"]
  "Videos and Moving Image Media": ["Images and Videos"]
  "Women's and Gender Studies": ["Social Sciences"]
  "Zoology": ["Biology"]
