---
# Options
#log-in:
- label: Log in to see more options
  service_type: Weblogin
  description:
    heading: Policies and additional details
    content:
      - TBD
  duration: TBD
  weight: 0
  grants:
    patron:
      - empty?
    holding:
      - can_request?

#contact-circulation:
- label: Contact Circulation
  description:
    heading: Policies and additional details
    content:
      - Your account with the University Library has expired
      - Are you a recent graduate?
      - Did you do a semester abroad?
      - Contact the circulation department for more information
      - TBD
  duration: TBD
  weight: 0
  form:
    type: link
    href: "https://www.lib.umich.edu/locations-and-hours/hatcher-library/hatcher-north-information-services-desk"
    text: Contact circulation
  grants:
    patron:
      - expired?
    holding:
      - can_request?

# Self Service (1 of 1)
- label: Find it in the library
  service_type: Self Service
  duration: Immediate access to a physical copy when the library is open
  description:
    heading: Policies and additional details
    content:
    - Find related items on the shelf
    - Staff assistance available on site
  grants:
    holding:
    - open_stacks?
    - on_shelf?
    - can_request?

# Contactless Pickup (1 of 4)
- label: Contactless pickup at the library
  service_type: Library pick up
  duration: Expected availability 1-5 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. Once checked-out, your item cannot be recalled by another user.
      - Learn more about <a href="https://lib.umich.edu/find-borrow-request/request-items-pick-or-delivery/contactless-pickup">contactless pickup</a>.
  form:
    type: alma_hold
    pickup_locations:
      - value: AAEL
        name: "Art, Architecture, & Engineering Library"
      - value: SHAP
        name: "Shapiro Undergraduate Library"
      - value: MUSIC
        name: "Music Library"
      - value: DRBN
        name: "Mardigan Library"
      - value: FLINT
        name: "Thompson Library"
  grants:
    holding:
      - ann_arbor?
      - on_shelf?
      - can_request?

# Contactless Pickup (2 of 4)
- label: Contactless pickup at the library
  service_type: Library pick up
  duration: Expected availability 1-10 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. Once checked-out, your item cannot be recalled by another user.
      - Learn more about <a href="https://lib.umich.edu/find-borrow-request/request-items-pick-or-delivery/contactless-pickup">contactless pickup</a>.
  form:
    type: alma_hold
    pickup_locations:
      - value: AAEL
        name: "Art, Architecture, & Engineering Library"
      - value: SHAP
        name: "Shapiro Undergraduate Library"
      - value: MUSIC
        name: "Music Library"
      - value: DRBN
        name: "Mardigan Library"
      - value: FLINT
        name: "Thompson Library"
  grants:
    patron:
      - ann_arbor_dearborn?
    holding:
      - flint?
      - on_shelf?
      - can_request?

# Contactless Pickup (3 of 4)
- label: Contactless pickup at the library
  service_type: Library pick up
  duration: Expected availability 1-2 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. Once checked-out, your item cannot be recalled by another user.
      - Curbside pick up is available at the Thompson Library. See <a href="https://umflint.libwizard.com/f/curbside">Thompson Library - Curbside Pick Up</a> for details.
  form:
    type: alma_hold
    pickup_locations:
      - value: AAEL
        name: "Art, Architecture, & Engineering Library"
      - value: SHAP
        name: "Shapiro Undergraduate Library"
      - value: MUSIC
        name: "Music Library"
      - value: DRBN
        name: "Mardigan Library"
      - value: FLINT
        name: "Thompson Library"
  grants:
    patron:
      - flint?
    holding:
      - flint?
      - on_shelf?
      - can_request?

# Contactless Pickup (4 of 4)
- label: Contactless pickup at the library
  service_type: Library pick up
  duration: Click to see additional details
  description:
    heading: Policies and additional details
    content:
      - Delivery time varies for items with status ON ORDER and notification will be sent when this item is available. <a href="https://ill.lib.umich.edu/illiad/illiad.dll?">Please make an interlibrary loan request if you need this item quickly</a>.
      - Standard loan and renewal policies apply. Once checked-out, your item cannot be recalled by another user.
      - Learn more about <a href="https://lib.umich.edu/find-borrow-request/request-items-pick-or-delivery/contactless-pickup">contactless pickup</a>.
  form:
    type: alma_hold
    pickup_locations:
      - value: AAEL
        name: "Art, Architecture, & Engineering Library"
      - value: SHAP
        name: "Shapiro Undergraduate Library"
      - value: MUSIC
        name: "Music Library"
      - value: DRBN
        name: "Mardigan Library"
      - value: FLINT
        name: "Thompson Library"
  grants:
    holding:
      - ann_arbor?
      - on_order?
      - can_request?

# Departmental Delivery (1 of 2)
- label: Have it delivered
  service_type: Document Delivery
  duration: Expected availability 1-7 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewals policies apply.
      - Set your delivery preference to your departmental mailbox via <a href="https://ill.lib.umich.edu/illiad/ChangeSite/ChangeSite.asp">ILLiad</a>.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - ann_arbor?
      - faculty_graduate_staff?
    holding:
      - ann_arbor?
      - on_shelf?
      - can_request?

# Departmental Delivery (2 of 2)
- label: Have it delivered
  service_type: Document Delivery
  duration: Expected availability 3-10 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewals policies apply.
      - Set your delivery preference to your departmental mailbox via <a href="https://ill.lib.umich.edu/illiad/ChangeSite/ChangeSite.asp">ILLiad</a>.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - ann_arbor?
      - faculty_graduate_staff?
    holding:
      - flint?
      - on_shelf?
      - can_request?

# Scan a portion (1 of 1)
- label: Request to have a small portion scanned (Document Delivery)
  service_type: Document Delivery
  duration: Expected availability 1-5 days
  description:
    heading: Policies and additional details
    content:
      - Requests to scan a portion are individually evaluated for copyright compliance.
      - Your requested portion will be available to you on a secure website for 2 weeks.
      - If the requested portion cannot be scanned because doing so would violate copyright law, a hold request for contactless pickup will be made on your behalf unless you specify otherwise in the notes field.
      - Microform scanning is limited.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelarticle
  grants:
    patron:
    - faculty_student_staff?
    bib:
    - can_scan?
    holding:
    - on_shelf?


# Interlibrary Loan (1 of 2)
- label: Request a copy from another library (Interlibrary Loan (I.L.L.))
  service_type: Document Delivery
  duration: Expected availability 5+ days
  description:
    heading: Policies and additional details
    content:
    - By default, items are delivered to Shapiro Library for contactless pickup.
    - Please note in your request if a physical copy cannot be used.
    - Requests may be filled via equivalent electronic resources.
    - Short-term loans
    - Limited renewals
    - "* Availability, checkout periods, and renewals depend on the lending institution."
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
    - ann_arbor?
    holding:
    - not_on_shelf?

# Interlibrary Loan (2 of 2)
- label: Request a copy from another library (Interlibrary Loan (I.L.L.))
  service_type: Document Delivery
  duration: Expected availability 7+ days
  description:
    heading: Policies and additional details
    content:
    - Please note in your request if a physical copy cannot be used.
    - Requests may be filled via equivalent electronic resources.
    - Short-term loans
    - Limited renewals
    - "* Availability, checkout periods, and renewals depend on the lending institution."
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
    - flint_dearborn?
    holding:
    - not_on_shelf?

