---
# Options
#log-in:
- label: Log in to see more options
  service_type: Weblogin
  description:
    heading: Policies and additional details
    content:
      - TBD
  duration: TBD
  weight: 0
  grants:
    patron:
      - empty?
    holding:
      - can_request?

#contact-circulation:
- label: Contact Circulation
  description:
    heading: Policies and additional details
    content:
      - Your account with the University Library has expired
      - Are you a recent graduate?
      - Did you do a semester abroad?
      - Contact the circulation department for more information
      - TBD
  duration: TBD
  weight: 0
  form:
    type: link
    href: "https://www.lib.umich.edu/locations-and-hours/hatcher-library/hatcher-north-information-services-desk"
    text: Contact circulation
  grants:
    patron:
      - expired?
    holding:
      - can_request?

# Self Service (1 of 1)
- label: Find it in the library
  service_type: Self Service
  duration: Immediate access to a physical copy when the library is open
  description:
    heading: Policies and additional details
    content:
    - Find related items on the shelf
    - Staff assistance available on site
  grants:
    holding:
    - open_stacks?
    - on_shelf?
    - can_request?

# Pickup (1 of 6)
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Expected availability 1-3 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. #Once checked-out, your item can be recalled by another user.
      - Can't find your book on the shelf? Request it for pickup, and we will search for it.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    patron:
      - active?
    holding:
      - ann_arbor?
      - on_shelf?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_game?

# Pickup (2 of 6)
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Expected availability 1-10 days
  description:
    heading: Policies and additional details
    content: 
      - Standard loan and renewal policies apply. #Once checked-out, your item can be recalled by another user.
      - Can't find your book on the shelf? Request it for pickup, and we will search for it.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    patron:
      - ann_arbor_dearborn?
    holding:
      - flint?
      - on_shelf?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_game?

# Pickup (3 of 6)
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Expected availability 1-2 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. Once checked-out, your item can be recalled by another user.
      - Can't find your book on the shelf? Request it for pickup, and we will search for it.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  FLINT
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  DBRN
  grants:
    patron:
      - flint?
    holding:
      - flint?
      - on_shelf?
      - can_request?
      - not_short_loan?
      - not_building_use_only?

# Pickup (4 of 6) WORK_ORDER_DEPARTMENT Labeling
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Click to see additional details
  description:
    heading: Policies and additional details
    content:
      - Delivery time varies for items with status IN A WORKORDER and notification will be sent when this item is available. <a href="https://ill.lib.umich.edu/illiad/illiad.dll?">Please make an interlibrary loan request if you need this item quickly</a>.
      - Standard loan and renewal policies apply. Once checked-out, your item can be recalled by another user.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    holding:
      - ann_arbor?
      - in_labeling?
      - can_request?
      - not_building_use_only?
      - not_game?

# Pickup (5 of 6) WORK_ORDER_DEPARTMENT AcqTechServices for ISEEES
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Expected availability 1-5 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. #Once checked-out, your item can be recalled by another user.
      - Can't find your book on the shelf? Request it for pickup, and we will search for it.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    holding:
      - ann_arbor?
      - in_international_studies_acquisitions_technical_services?
      - can_request?
        
# Pickup (6 of 6)
- label: Pick it up at the library
  service_type: Library-to-library
  duration: Click to see additional details
  description:
    heading: Policies and additional details
    content:
      - "Delivery time varies for items with status \"In Process: ACQ.\" A notification will be sent when this item is available. <a href=\"https://ill.lib.umich.edu/illiad/illiad.dll?\">Please make an interlibrary loan request if you need this item quickly</a>."
      - Standard loan and renewal policies apply. Once checked-out, your item can be recalled by another user.
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
  form:
    type: alma_hold
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    holding:
      - ann_arbor?
      - in_acq?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_game?

# Departmental Delivery (1 of 2)
- label: Have it delivered
  service_type: Document Delivery
  duration: Expected availability 1-7 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewals policies apply.
      - Set your delivery preference to your departmental mailbox via <a href="https://ill.lib.umich.edu/illiad/ChangeSite/ChangeSite.asp">ILLiad</a>.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - ann_arbor?
      - faculty_graduate_staff?
    holding:
      - ann_arbor?
      - on_shelf?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_reservable_library?
      - not_game?

# Departmental Delivery (2 of 2)
- label: Have it delivered
  service_type: Document Delivery
  duration: Expected availability 3-10 days
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewals policies apply.
      - Set your delivery preference to your departmental mailbox via <a href="https://ill.lib.umich.edu/illiad/ChangeSite/ChangeSite.asp">ILLiad</a>.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - ann_arbor?
      - faculty_graduate_staff?
    holding:
      - flint?
      - on_shelf?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_reservable_library?
      - not_game?

# Scan a portion (1 of 1)
- label: Request to have a small portion scanned (Document Delivery)
  service_type: Document Delivery
  duration: Expected availability 1-5 days
  description:
    heading: Policies and additional details
    content:
      - Your requested portion will be available to you on a secure website for 2 weeks.
      - Requests to scan a portion are individually evaluated for copyright compliance. Requests that can't be scanned due to copyright law may be offered as physical loans.
      - Microform scanning is limited.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelarticle
  grants:
    patron:
      - faculty_student_staff?
    bib:
      - can_scan?


# Interlibrary Loan (1 of 2)
- label: Request a copy from another library (Interlibrary Loan (I.L.L.))
  service_type: Document Delivery
  duration: Expected availability 5+ days
  description:
    heading: Policies and additional details
    content:
      - Requests may be filled via equivalent electronic resources.
      - Limited renewals
      - Availability, checkout periods, and renewals depend on the lending institution.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - ann_arbor?
    holding:
      - not_on_shelf?
      - not_reservable_library?

# Interlibrary Loan (2 of 2)
- label: Request a copy from another library (Interlibrary Loan (I.L.L.))
  service_type: Document Delivery
  duration: Expected availability 7+ days
  description:
    heading: Policies and additional details
    content:
      - Requests may be filled via equivalent electronic resources.
      - Limited renewals
      - Availability, checkout periods, and renewals depend on the lending institution.
  form:
    type: illiad_request
    fields:
      - name: genre
        value: docdelbook
  grants:
    patron:
      - flint_dearborn?
    holding:
      - not_on_shelf?
      - not_reservable_library?

# Place a future reservation
# Media Booking
- label: Place a future reservation
  service_type: Media Reservations
  duration: Expected availability 1-3 days
  description: 
    heading: Policies and additional details
    content:
      - Reservations for items on the shelf are subject to a 2-3 business day lead time (up to 10 business days when the item is currently checked out.)
      - You will not be able to reserve an item if it is already reserved by someone else.
      - If you need a video for a class sooner than the first eligible date or have any other questions, please contact <a href="https://www.lib.umich.edu/locations-and-hours/askwith-media-library">Askwith Media Library</a>.
  form:
    type: reservation
    base: "https://get-this.lib.umich.edu/"
    text: Place reservation
  grants:
    patron:
      - faculty_graduate_staff?
      - active?
    bib:
      - reservable_format?
    holding:
      - reservable_library?

# Recall (1 of 2)
- label: Request that this copy be returned
  service_type: Library-to-library
  duration: Expected availability 1-3 weeks*
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. 
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
      - "* A new due date will be given for this item."
  form:
    type: alma_recall
    pickup_locations:
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  FLINT
      -  DBRN
  grants:
    patron:
      - active?
    holding:
      - ann_arbor?
      - recallable?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_reservable_library?

# Recall (2 of 2)
- label: Request that this copy be returned
  service_type: Library pick up
  duration: Expected availability 1-3 weeks*
  description:
    heading: Policies and additional details
    content:
      - Standard loan and renewal policies apply. 
      - The Hatcher pickup desk in the North Lobby is less accessible than our other locations. Please enter by the Hatcher South entrance, or select Shapiro pickup instead, for the most accessible approach to the pickup desk.
      - Find out more about all pickup desks and <a href="https://www.lib.umich.edu/locations-and-hours">Library locations</a>.
      - "* A new due date will be given for this item."
  form:
    type: alma_recall
    pickup_locations:
      -  FLINT
      -  SHAP
      -  AAEL
      -  DHCL
      -  FINE
      -  HATCH
      -  MUSM
      -  MUSIC
      -  TAUB
      -  DBRN
  grants:
    patron:
      - flint?
    holding:
      - flint?
      - recallable?
      - can_request?
      - not_short_loan?
      - not_building_use_only?
      - not_reservable_library?
