---
AAEL: 168377
AAEL BKS: 0
AAEL CAR: 243
AAEL DISP: 45
AAEL EQAAEL: 2
AAEL FUN: 477
AAEL MAIN: 141191
AAEL MICE: 1641
AAEL MICM: 504
AAEL NONE: 54
AAEL OVR: 2477
AAEL RAR: 2902
AAEL REF: 522
AAEL RESC: 85
AAEL RESI: 139
AAEL RESP: 1773
AAEL SECD: 9796
AAEL SERU: 328
AAEL SLD: 153
AAEL STO: 7779
AAEL STOF: 1879
AAEL STUDIO: 38
BENT: 59684
BENT ELEC: 14
BENT NONE: 57593
BENT RR: 304
BENT SF: 450
BENT STOR: 1596
BSTA: 8780
BSTA CAGE: 42
BSTA NONE: 8515
BSTA OVR: 51
BSTA REF: 182
BSTA RESC: 59
BUHR: 2440215
CLEM: 110109
CLEM NONE: 92278
CLEM RBR: 3779
CLEM RSTO: 14413
DHCL: 35917
DHCL BOOK: 1955
DHCL BRD: 4040
DHCL CDROM: 16
DHCL DISC: 20
DHCL DVD: 25675
DHCL DVROM: 1
DHCL GAME: 10
DHCL LASER: 191
DHCL OVR: 10
DHCL SCRN: 3760
DHCL TAPEC: 2
DHCL VHS: 261
ELEC: 5672185
FINE: 82917
FINE ADM: 408
FINE EQFINE: 2
FINE FOL: 3
FINE MAIN: 78885
FINE NEW: 1316
FINE OSR: 7
FINE OVR: 1646
FINE REF: 1432
FINE RESC: 4
FINE RESP: 41
FINE SER: 784
FINE SERU: 70
FINE SPE: 20
FLINT: 254218
FLINT ARCH: 2995
FLINT ATLAS: 34
FLINT BROWS: 459
FLINT CHILD: 5623
FLINT DISP: 218
FLINT ELEC: 9
FLINT ELP: 522
FLINT FSPAM: 1055
FLINT MAIN: 226498
FLINT MEDIA: 4806
FLINT MICRO: 6341
FLINT MODEL: 43
FLINT MSTR: 771
FLINT NEWB: 152
FLINT NONE: 70
FLINT OVERZ: 1232
FLINT PERI: 1996
FLINT REF: 2058
FLINT RESV: 148
FVL: 56978
FVL BUH: 3259
FVL ELL: 13306
FVL EQASKW: 2
FVL F2: 1
FVL H1: 42199
FVL NONE: 134
FVL RESC: 207
GRAD: 1
HATCH: 2035593
HATCH AMHC: 390
HATCH AOKA: 2736
HATCH ASIA: 286100
HATCH CLARK: 5274
HATCH CLATL: 2570
HATCH CLBKS: 7524
HATCH CLBKS-CIRC: 21
HATCH CLC: 15045
HATCH CLFIL: 8534
HATCH CLFIR: 607
HATCH CLFOL: 870
HATCH CLMAP: 42821
HATCH CLOFF: 23
HATCH CLOS: 18276
HATCH CLOVD: 348
HATCH CLOVR: 135
HATCH CLRAR: 3563
HATCH CLSOF: 364
HATCH DISP-C: 19
HATCH DISP-I: 1
HATCH DISP-N: 4
HATCH EQHATC: 5
HATCH GFOL: 3081
HATCH GLMR: 116563
HATCH GRAD: 1494608
HATCH IS-SEEES: 18839
HATCH MIXM: 35
HATCH MONO: 157
HATCH NER: 471
HATCH NONE: 405
HATCH PAPY: 3113
HATCH REF: 7479
HATCH SAR: 387
HATCH SEAR: 421
HATCH SEM: 531
HATCH SLVR: 134
HATCH SLVRH: 13
HSRS: 245817
HSRS BUHR: 2256
HSRS IND: 41
HSRS NONE: 181925
HSRS OFFS: 37681
HSRS OVR: 754
HSRS SCI: 1058
HSRS SER: 18036
HSRS STOR: 4913
MAIN: 3
MIC: 1
MIU: 7760645
MUSIC: 229647
MUSIC DIS: 13
MUSIC DVD: 3916
MUSIC EDIS: 36270
MUSIC EQMUSI: 2
MUSIC FOLIO: 38
MUSIC MINI: 2502
MUSIC NEW: 54
MUSIC NONE: 113137
MUSIC OVCD: 168
MUSIC OVR: 859
MUSIC RAR: 7284
MUSIC RARS: 13137
MUSIC RARW: 2802
MUSIC REC: 47651
MUSIC REF: 2416
MUSIC RESC: 88
MUSIC SERU: 77
MUSIC SOFT: 90
MUSIC VID: 8
MUSM: 40532
MUSM ANT: 5496
MUSM ANTE: 119
MUSM ANTO: 60
MUSM BIR: 7027
MUSM BIRC: 287
MUSM CAGE: 585
MUSM FIS: 2403
MUSM FISO: 58
MUSM HEBC: 6
MUSM HEBO: 34
MUSM HEBR: 59
MUSM HEP: 1221
MUSM HEPO: 18
MUSM HERB: 11980
MUSM INS: 3618
MUSM INSO: 61
MUSM MAIN: 84
MUSM MAM: 1596
MUSM MAMO: 40
MUSM MIC: 1
MUSM MOL: 1113
MUSM MOLO: 27
MUSM NONE: 73
MUSM OVR: 1
MUSM PAL: 4579
MUSM PALO: 232
MUSM PALR: 84
MUSM SPE: 40
OFFS: 317873
OFFS DEEP: 786
OFFS ELLS: 204699
OFFS SPR: 55
OFFS STATE: 112532
OFFS UNASSIGNED: 2
RES_SHARE: 5144
RES_SHARE IN_RS_REQ: 3964
RES_SHARE MELLONG: 293
RES_SHARE MELREG: 890
SDR: 3
SDR EO: 2
SDR UMLAW: 1
SHAP: 501653
SHAP ATL: 7124
SHAP COLSC: 1001
SHAP DIS: 10
SHAP DISP: 83
SHAP DLAB: 97
SHAP EQSHAP: 6
SHAP FLOW: 50641
SHAP GAME: 10715
SHAP GAMEB: 316
SHAP GOV: 64759
SHAP MAS: 1
SHAP OVR: 123
SHAP PRON: 5408
SHAP REFU: 8
SHAP RESP: 513
SHAP SCI: 144245
SHAP SER: 6134
SHAP SERU: 112
SHAP SOVR: 353
SHAP UGL: 212706
SPEC: 267475
SPEC BIND: 428
SPEC CHIL: 26418
SPEC CUL: 8716
SPEC FAUL: 1553
SPEC JHC: 2337
SPEC LABD: 81852
SPEC NONE: 159
SPEC RARE: 87485
SPEC REF: 727
SPEC SCB-AMS: 296
SPEC SCB-ASG: 1105
SPEC SCB-GOSL: 2833
SPEC SCB-HAFTR: 202
SPEC SCB-HAFTRO: 1
SPEC SCB-HUB: 2838
SPEC SCB-HUBO: 1
SPEC SCB-MYERS: 2731
SPEC SCB-PARS: 1714
SPEC SCB-SCFI: 3670
SPEC SCB-SHA: 6177
SPEC SCB-WALP: 4584
SPEC SCB-WALPO: 1815
SPEC SCH-AMS: 2148
SPEC SCH-ISLM: 1241
SPEC SCH-MICH: 278
SPEC TAUB: 8060
SPEC THC: 17693
SPEC WOR: 1629
TAUB: 74
TAUB EQTAUB: 2
TAUB NONE: 46
TAUB REF: 5
TAUB RESC: 21
