get_this:
  - code: "AAEL"
    text: "Art, Architecture, & Engineering Library"
  - code: "DHCL"
    text: "Donald Hall Collection"
  - code: "FINE"
    text: "Fine Arts"
  - code: "HATCH"
    text: "Hatcher Library (Use Shapiro for wheelchair access)"
  - code: "MUSM"
    text: "Museums"
  - code: "MUSIC"
    text: "Music Library"
  - code: "SHAP"
    text: "Shapiro Library"
  - code: "TAUB"
    text: "Taubman Health Sciences"
  - code: "FLINT"
    text: "Thompson Library (UM-Flint)"
  - code: "DBRN"
    text: "Mardigian Library (UM-Dearborn)"

