---
- id: mirlyn
  name: Mirlyn
  type: solr
  url: <%= ENV['SPECTRUM_CATALOG_SOLR_URL'] %>
  holdings: <%= ENV['SPECTRUM_CATALOG_HOLDINGS_URL'] %>
  truncate: true
  driver: RSolr
  link_type: rebase
  link_base: http://mirlyn.lib.umich.edu/Record
  conditionals:
    search_only?: '+(ht_searchonly:false OR availability:"Full text available (log in required)" OR availability:"Full text available (HathiTrust log in required)")'
    available_online?: '+availability:("Available online" OR "Full text available (log in required)" OR "Full text available (HathiTrust log in required)")'
- id: website
  name: Website
  type: solr
  url: <%= ENV['SPECTRUM_WEBSITE_SOLR_URL'] %>
  truncate: true
  driver: RSolr
  link_type: :rebase
  link_base: https://www.lib.umich.edu
  link_key: path_alias
- id: summon
  name: ArticlesPlus
  type: summon
  url: <%= ENV['SPECTRUM_SUMMON_URL'] %>
  driver: Summon
  access_id: <%= ENV['SPECTRUM_SUMMON_ID'] %>
  secret_key: <%= ENV['SPECTRUM_SUMMON_SECRET_KEY'] %>
