---
- id: mirlyn
  name: Mirlyn
  type: solr
  url: <%= ENV['SPECTRUM_CATALOG_SOLR_URL'] %>
  holdings: '' #mrio: I don't know how to get rid of this
  truncate: true
  driver: RSolr
  link_type: rebase
  link_base: http://mirlyn.lib.umich.edu/Record
  conditionals:
    not_search_only?: '+(new_availability:physical OR new_availability:hathi_trust_full_text_or_electronic_holding)'
    available_online?: '+availability:("Available online" OR "Full text available (log in required)" OR "Full text available (HathiTrust log in required)")'
- id: website
  name: Website
  type: solr
  url: <%= ENV['SPECTRUM_WEBSITE_SOLR_URL'] %>
  truncate: true
  driver: RSolr
  link_type: rebase
  link_base: https://www.lib.umich.edu
  link_key: path_alias
- id: summon
  name: ArticlesPlus
  type: summon
  url: 'should_not_need_this_anymore' 
  driver: Summon
  access_id: 'should_not_need_this_anymore' 
  secret_key: 'should_not_need_this_anymore' 
- id: primo
  name: Primo
  type: primo
  key: <%= ENV['SPECTRUM_PRIMO_KEY'] %>
  host: <%= ENV['SPECTRUM_PRIMO_HOST'] %>
  tab: <%= ENV['SPECTRUM_PRIMO_TAB'] %>
  scope: <%= ENV['SPECTRUM_PRIMO_SCOPE'] %>
  view: <%= ENV['SPECTRUM_PRIMO_VIEW'] %>
  libkey:
    host: <%= ENV['SPECTRUM_LIBKEY_HOST'] %>
    key: <%= ENV['SPECTRUM_LIBKEY_KEY'] %>
    library_id: <%= ENV['SPECTRUM_LIBKEY_LIBRARY_ID'] %>
