name: Build latest spectrum-unstable on push

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Log into Github Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push spectrum
      env:
        IMAGE_NAME: spectrum-unstable
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:latest
           ghcr.io/mlibrary/${{ env.IMAGE_NAME }}:${{ github.sha }}
