name: Docker Build Latest Commit

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build container image and push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 'bertrama/spectrum-unstable:${{ github.sha }},bertrama/spectrum-unstable:latest'
        file: Dockerfile
    - name: Image digest
      run: |
        echo '${{ steps.docker_build.outputs.digest }}'
